
spring:
  #  jdbc config files
  datasource:
    name: expeditors-training
    url: jdbc:postgresql://localhost:5432/ems
    username: postgres
    password: dragon
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout : 20000
      idleTimeout: 600000
      maxLifetime: 18000
      maximum-pool-size : 20
      register- mbeans: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
